### ISSUE TITLE
Evaluate adding support for System.ServiceProcess classes

### ISSUE THREAD

**Issue by cbenard** [flamencist/Core.System.Configuration.Install#2]
I worked with Microsoft people to get System.ServiceProcess [added to the reference source](https://github.com/dotnet/corefx/issues/37903). This gives us `ServiceInstaller` and `ServiceProcessInstaller` and their dependents.

@flamencist suggested possibly adding support in this NuGet package, but since it's a separate assembly, I think a new repo/NuGet should be created for it that has this repo/NuGet (Core.System.Configuration.Install) as a dependency, so people can take just the classes they want into their `netstandard2.0` environment.

Thoughts?

**Comment by cbenard** [comment]
@flamencist any interest in doing this? I'm at a point now where I either need `ServiceInstaller` and `ServiceProcessInstaller` or I'm going to have to re-do a bunch of stuff in Win32 P/Invoke myself to replace functionality.

**Comment by flamencist** [comment]
I'll appreciate if you help me with this. Unfortunately, I haven't extra time now.

**Comment by cbenard** [comment]
This is [now done](https://github.com/cbenard/Core.System.ServiceProcess) but untested.

You can close this issue though. Please feel free to do PRs on it.
