### ISSUE TITLE
Where did the original source code come from?

### ISSUE THREAD

**Issue by TechnikEmpire** [flamencist/Core.System.Configuration.Install#3]
Just out of curiosity. I'm concerned about the original source license.

**Comment by flamencist** [comment]
It's port for dotnet core of decompiled .NET 4.5

**Comment by TechnikEmpire** [comment]
Ah OK. Just FYI the license terms of that code is MS-RSL, which explicitly forbids any other use except for reference. So based on what you're saying this source code is copyright infringement and will get people sued.
