### ISSUE TITLE
Ambigous PerformanceCounter types.

### ISSUE THREAD

**Issue by zgabi** [flamencist/Core.System.Configuration.Install#5]
Hi,

I'm receiving the following compile errors in my project:
error CS0433: The type 'PerformanceCounterCategoryType' exists in both 'System.Configuration.Install, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' and 'System.Diagnostics.PerformanceCounter, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

Because I'm using the System.Diagnostics.PerformanceCounter nuget package (in a dependecy project), too.

I think it would be better if your project will reference those packages instead copying the source code.

Would you accept a PR for this?

I created a fork, and also a nuget package with this change:
https://github.com/zgabi/Core.System.Configuration.Install/commit/615c916bf810e4edbde8e40bd7d85c46b34cffce

https://www.nuget.org/packages/ZGabi.Core.System.Configuration.Install/1.0.1 (Of course I'll make this deprecated if you accept a PR)

And EventSourceCreationData exists in System.Diagnostics.EventLog package, however it did not caused any problem for me, but I think it is good to use the official for that class, too.

Thanks, 
Gábor

**Comment by flamencist** [comment]
Hello! I will be very appreciate if you create PR.

**Comment by zgabi** [comment]
Thank you.
